export { default as authRoutes } from './auth.routes'
export { default as examRoutes } from './exam.routes'
export { default as venueRoutes } from './venue.routes'
export { default as approvalRoutes } from './approval.routes'
export { default as falRoutes } from './fal.routes'
export { default as financeRoutes } from './finance.routes'
export { default as fieldReportRoutes } from './field-report.routes'
export { default as fieldRoutes } from './field.routes'
export { default as materialRoutes } from './material.routes'
export { default as inspectionRoutes } from './inspection.routes'
export { default as surveyRoutes } from './survey.routes'
export { default as faceauthRoutes } from './faceauth.routes'
export { cockpitRouter, reportRouter } from './cockpit.routes'
export { default as candidateRoutes } from './candidate.routes'
export { default as admitCardRoutes } from './admitcard.routes'
